/**:
  ros__parameters:
    tolerance: 0.5
    voxel_leaf_size: 0.05
    min_points_number_per_voxel: 1
    min_cluster_size: 4
    max_cluster_size: 3000
    use_height: true
    input_frame: "base_link"

    # low height crop box filter param
    max_x: 8.0
    min_x: -6.0
    max_y: 2.0                                                                                                                                    
    min_y: -2.0
    max_z: 1.0
    min_z: -1.3
